[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = '''
      default-src 'self' https:;
      connect-src 'self';
      object-src 'none';
      style-src  'self' 'unsafe-inline' unpkg.com;
      script-src 'self' 'unsafe-inline';
      frame-ancestors https://www.wfac2020.o/rg;'''
